// Code generated by "stringer -type=ComparisonOperator"; DO NOT EDIT.

package nodes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComparisonOperatorOr-0]
	_ = x[ComparisonOperatorAnd-1]
}

const _ComparisonOperator_name = "ComparisonOperatorOrComparisonOperatorAnd"

var _ComparisonOperator_index = [...]uint8{0, 20, 41}

func (i ComparisonOperator) String() string {
	if i < 0 || i >= ComparisonOperator(len(_ComparisonOperator_index)-1) {
		return "ComparisonOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComparisonOperator_name[_ComparisonOperator_index[i]:_ComparisonOperator_index[i+1]]
}
