// Code generated by "stringer -type=ComparisonOperator"; DO NOT EDIT.

package nodes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComparisonOperatorEquals-0]
	_ = x[ComparisonOperatorNotEquals-1]
	_ = x[ComparisonOperatorLessThan-2]
	_ = x[ComparisonOperatorLessThanOrEqual-3]
	_ = x[ComparisonOperatorGreaterThan-4]
	_ = x[ComparisonOperatorGreaterThanOrEqual-5]
}

const _ComparisonOperator_name = "ComparisonOperatorEqualsComparisonOperatorNotEqualsComparisonOperatorLessThanComparisonOperatorLessThanOrEqualComparisonOperatorGreaterThanComparisonOperatorGreaterThanOrEqual"

var _ComparisonOperator_index = [...]uint8{0, 24, 51, 77, 110, 139, 175}

func (i ComparisonOperator) String() string {
	if i < 0 || i >= ComparisonOperator(len(_ComparisonOperator_index)-1) {
		return "ComparisonOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComparisonOperator_name[_ComparisonOperator_index[i]:_ComparisonOperator_index[i+1]]
}
