// Code generated by "stringer -type=EqualityOperator"; DO NOT EDIT.

package nodes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EqualityOperatorEquals-0]
	_ = x[EqualityOperatorNotEquals-1]
	_ = x[EqualityOperatorLessThan-2]
	_ = x[EqualityOperatorLessThanOrEqual-3]
	_ = x[EqualityOperatorGreaterThan-4]
	_ = x[EqualityOperatorGreaterThanOrEqual-5]
}

const _EqualityOperator_name = "EqualityOperatorEqualsEqualityOperatorNotEqualsEqualityOperatorLessThanEqualityOperatorLessThanOrEqualEqualityOperatorGreaterThanEqualityOperatorGreaterThanOrEqual"

var _EqualityOperator_index = [...]uint8{0, 22, 47, 71, 102, 129, 163}

func (i EqualityOperator) String() string {
	if i < 0 || i >= EqualityOperator(len(_EqualityOperator_index)-1) {
		return "EqualityOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EqualityOperator_name[_EqualityOperator_index[i]:_EqualityOperator_index[i+1]]
}
