// Code generated by "stringer -type=MultiplicativeOperator"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MultiplicativeOperatorMultiplication-0]
	_ = x[MultiplicativeOperatorDivision-1]
}

const _MultiplicativeOperator_name = "MultiplicativeOperatorMultiplicationMultiplicativeOperatorDivision"

var _MultiplicativeOperator_index = [...]uint8{0, 36, 66}

func (i MultiplicativeOperator) String() string {
	if i < 0 || i >= MultiplicativeOperator(len(_MultiplicativeOperator_index)-1) {
		return "MultiplicativeOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MultiplicativeOperator_name[_MultiplicativeOperator_index[i]:_MultiplicativeOperator_index[i+1]]
}
