// Code generated by "stringer -type=UnaryOperator"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnaryOperatorSubtraction-0]
	_ = x[UnaryOperatorNot-1]
	_ = x[UnaryOperatorSpread-2]
}

const _UnaryOperator_name = "UnaryOperatorSubtractionUnaryOperatorNotUnaryOperatorSpread"

var _UnaryOperator_index = [...]uint8{0, 24, 40, 59}

func (i UnaryOperator) String() string {
	if i < 0 || i >= UnaryOperator(len(_UnaryOperator_index)-1) {
		return "UnaryOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnaryOperator_name[_UnaryOperator_index[i]:_UnaryOperator_index[i+1]]
}
