// Code generated by "stringer -type=Trait"; DO NOT EDIT.

package semantics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TraitNone-0]
	_ = x[TraitNumeric-1]
	_ = x[TraitCallable-2]
	_ = x[TraitAny-4]
	_ = x[TraitAlias-8]
	_ = x[TraitImport-16]
	_ = x[TraitString-32]
}

const (
	_Trait_name_0 = "TraitNoneTraitNumericTraitCallable"
	_Trait_name_1 = "TraitAny"
	_Trait_name_2 = "TraitAlias"
	_Trait_name_3 = "TraitImport"
	_Trait_name_4 = "TraitString"
)

var (
	_Trait_index_0 = [...]uint8{0, 9, 21, 34}
)

func (i Trait) String() string {
	switch {
	case i <= 2:
		return _Trait_name_0[_Trait_index_0[i]:_Trait_index_0[i+1]]
	case i == 4:
		return _Trait_name_1
	case i == 8:
		return _Trait_name_2
	case i == 16:
		return _Trait_name_3
	case i == 32:
		return _Trait_name_4
	default:
		return "Trait(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
